import { ActivityCategory } from './activity';
import { GoalStatus } from './goal';
import { OrganizationInviteStatus, OrganizationMemberRole } from './organization';

export const LogTemplates = {
  USER_REGISTER_START: 'User[email={email}] register start',
  USER_REGISTER_SUCCESS: 'User[id={id}] register success in region={region}',
  USER_REGISTER_FAILED: 'User[email={email}] register failed: {reason}',
  USER_LOGIN_START: 'User[email={email}] login start',
  USER_LOGIN_SUCCESS: 'User[id={id}] login success roles={roles}',
  USER_LOGIN_FAILED: 'User[email={email}] login failed: {reason}',
  USER_PROFILE_UPDATE_START: 'User[id={id}] profile update start field={field}',
  USER_PROFILE_UPDATE_SUCCESS: 'User[id={id}] profile update success region={region}',
  USER_PROFILE_UPDATE_FAILED: 'User[id={id}] profile update failed field={field}: {reason}',
  ACTIVITY_LIST_START: `Activity list start category values=${Object.values(ActivityCategory).join(',')}`,
  ACTIVITY_CREATE_START: 'Activity[user_id={userId}] create start category={category} sub_type={subType}',
  ACTIVITY_CREATE_SUCCESS: 'Activity[id={id}] create success carbon_value={carbonValue}',
  ACTIVITY_CREATE_FAILED: 'Activity[id={id}] create failed: {field} {reason}',
  ACTIVITY_UPDATE_START: 'Activity[id={id}] update start fields={fields}',
  ACTIVITY_UPDATE_SUCCESS: 'Activity[id={id}] update success carbon_value={carbonValue}',
  ACTIVITY_UPDATE_FAILED: 'Activity[id={id}] update failed: {field} {reason}',
  ACTIVITY_DELETE_SUCCESS: 'Activity[id={id}] delete success',
  GOAL_LIST_START: `Goal list start statuses=${Object.values(GoalStatus).join(',')}`,
  GOAL_CREATE_START: 'Goal[user_id={userId}] create start status={status}',
  GOAL_CREATE_SUCCESS: 'Goal[id={id}] create success target_value={targetValue}',
  GOAL_CREATE_FAILED: 'Goal[id={id}] create failed: {field} {reason}',
  GOAL_PROGRESS_CALCULATED: 'Goal[id={id}] progress calculated current={currentValue} target={targetValue}',
  ORG_LIST_START: `Organization list start invite_statuses=${Object.values(OrganizationInviteStatus).join(',')} member_roles=${Object.values(OrganizationMemberRole).join(',')}`,
  ORG_CREATE_START: 'Organization[name={name}] create start user_id={userId}',
  ORG_CREATE_SUCCESS: 'Organization[id={id}] create success name={name}',
  ORG_CREATE_FAILED: 'Organization[id={id}] create failed: {field} {reason}',
  ORG_INVITE_ISSUE_START: 'OrganizationInvite[org_id={orgId}] issue start user_id={userId}',
  ORG_INVITE_ISSUE_SUCCESS: 'OrganizationInvite[id={id}] issue success org_id={orgId}',
  ORG_INVITE_ISSUE_FAILED: 'OrganizationInvite[id={id}] issue failed: {field} {reason}',
  ORG_INVITE_REDEEM_START: 'OrganizationInvite[code={code}] redeem start user_id={userId}',
  ORG_INVITE_REDEEM_SUCCESS: 'OrganizationInvite[id={id}] redeem success org_id={orgId} user_id={userId}',
  ORG_INVITE_REDEEM_FAILED: 'OrganizationInvite[code={code}] redeem failed: {field} {reason}',
  ORG_LEAVE_SUCCESS: 'OrganizationMembership[id={id}] leave success org_id={orgId} user_id={userId}',
  ORG_MEMBER_REMOVE_SUCCESS: 'OrganizationMembership[id={id}] remove success org_id={orgId} user_id={userId}',
  ORG_SUMMARY_CALCULATED: 'Organization[id={id}] summary calculated month={month} total={total}',
  ORG_ACCESS_DENIED: 'Organization[id={id}] access denied user_id={userId}: {reason}',
  FACTOR_LIST_START: `CarbonFactor list start categories=${Object.values(ActivityCategory).join(',')}`,
  FACTOR_CREATE_SUCCESS: 'CarbonFactor[id={id}] create success category={category} region={region}',
  FACTOR_CREATE_FAILED: 'CarbonFactor[id={id}] create failed: {field} {reason}',
  AUDIT_WRITE_START: 'AuditLog[entity={entity}] write start action={action}',
  AUDIT_WRITE_SUCCESS: 'AuditLog[id={id}] write success entity={entity}',
  AUDIT_WRITE_FAILED: 'AuditLog[entity={entity}] write failed: {reason}',
  AUTH_GUARD_GRANTED: 'Auth[user_id={id}] guard granted',
  AUTH_GUARD_DENIED: 'Auth[token={token}] guard denied: {reason}',
  RBAC_GRANTED: 'RBAC[user_id={id}] role granted required={roles}',
  RBAC_DENIED: 'RBAC[user_id={id}] role denied required={roles}',
  HEALTH_CHECK: 'System[health] backend health check'
} as const;

export type LogTemplateKey = keyof typeof LogTemplates;

